### ISSUE TITLE
Length of a number and null are allowed

### ISSUE THREAD

**Issue by afmika** [luckasRanarison/icelang#5]
```
length(null) -- null
length(1234) -- null
type_of(length(<any>)) -- always a "number" or throw an error if not iterable/countable
```

**Comment by luckasRanarison** [comment]
I've decided to leave the number type for length() because of floating issues but you are right I should have made error for these. But what do you exactly mean by the last one?

**Comment by afmika** [comment]
As a user, I would expect built-in functions such as `length`, `min`, `max`, etc. to always produce a number, a `NaN` or throw an error but never a null.
